[2025-05-28T10:03:23.235+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: full_training_pipeline.trigger_register_best_model manual__2025-05-28T10:02:14.318608+00:00 [queued]>
[2025-05-28T10:03:23.251+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: full_training_pipeline.trigger_register_best_model manual__2025-05-28T10:02:14.318608+00:00 [queued]>
[2025-05-28T10:03:23.252+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-05-28T10:03:23.263+0000] {taskinstance.py:2217} INFO - Executing <Task(TriggerDagRunOperator): trigger_register_best_model> on 2025-05-28 10:02:14.318608+00:00
[2025-05-28T10:03:23.271+0000] {standard_task_runner.py:60} INFO - Started process 20734 to run task
[2025-05-28T10:03:23.283+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'full_training_pipeline', 'trigger_register_best_model', 'manual__2025-05-28T10:02:14.318608+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/full_pipeline.py', '--cfg-path', '/tmp/tmp5pprths2']
[2025-05-28T10:03:23.288+0000] {standard_task_runner.py:88} INFO - Job 31: Subtask trigger_register_best_model
[2025-05-28T10:03:23.336+0000] {task_command.py:423} INFO - Running <TaskInstance: full_training_pipeline.trigger_register_best_model manual__2025-05-28T10:02:14.318608+00:00 [running]> on host bbc28cef36b5
[2025-05-28T10:03:23.391+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='full_training_pipeline' AIRFLOW_CTX_TASK_ID='trigger_register_best_model' AIRFLOW_CTX_EXECUTION_DATE='2025-05-28T10:02:14.318608+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-28T10:02:14.318608+00:00'
[2025-05-28T10:03:23.439+0000] {trigger_dagrun.py:210} INFO - Waiting for register_best_model_from_mlflow on 2025-05-28 10:03:23.391583+00:00 to become allowed state ['success'] ...
[2025-05-28T10:04:23.483+0000] {trigger_dagrun.py:210} INFO - Waiting for register_best_model_from_mlflow on 2025-05-28 10:03:23.391583+00:00 to become allowed state ['success'] ...
[2025-05-28T10:05:23.526+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/trigger_dagrun.py", line 221, in execute
    raise AirflowException(f"{self.trigger_dag_id} failed with failed states {state}")
airflow.exceptions.AirflowException: register_best_model_from_mlflow failed with failed states failed
[2025-05-28T10:05:23.535+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=full_training_pipeline, task_id=trigger_register_best_model, execution_date=20250528T100214, start_date=20250528T100323, end_date=20250528T100523
[2025-05-28T10:05:23.555+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 31 for task trigger_register_best_model (register_best_model_from_mlflow failed with failed states failed; 20734)
[2025-05-28T10:05:23.594+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-28T10:05:23.641+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
