[2025-05-28T07:38:12.461+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_ml_models.train_and_log_models manual__2025-05-28T07:37:07.089789+00:00 [queued]>
[2025-05-28T07:38:12.466+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_ml_models.train_and_log_models manual__2025-05-28T07:37:07.089789+00:00 [queued]>
[2025-05-28T07:38:12.466+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2025-05-28T07:38:12.478+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): train_and_log_models> on 2025-05-28 07:37:07.089789+00:00
[2025-05-28T07:38:12.490+0000] {standard_task_runner.py:60} INFO - Started process 3314 to run task
[2025-05-28T07:38:12.497+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'train_ml_models', 'train_and_log_models', 'manual__2025-05-28T07:37:07.089789+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/train_models.py', '--cfg-path', '/tmp/tmp7v_114zg']
[2025-05-28T07:38:12.501+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask train_and_log_models
[2025-05-28T07:38:12.546+0000] {task_command.py:423} INFO - Running <TaskInstance: train_ml_models.train_and_log_models manual__2025-05-28T07:37:07.089789+00:00 [running]> on host 6bb48dadf8eb
[2025-05-28T07:38:12.602+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='train_ml_models' AIRFLOW_CTX_TASK_ID='train_and_log_models' AIRFLOW_CTX_EXECUTION_DATE='2025-05-28T07:37:07.089789+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-28T07:37:07.089789+00:00'
[2025-05-28T07:38:14.353+0000] {logging_mixin.py:188} INFO - üß™ –í—ã–ø–æ–ª–Ω—è–µ–º dvc pull...
[2025-05-28T07:38:14.359+0000] {logging_mixin.py:188} INFO - STDOUT: Everything is up to date.
[2025-05-28T07:38:14.359+0000] {logging_mixin.py:188} INFO - STDERR: 
[2025-05-28T07:38:15.269+0000] {migration.py:216} INFO - Context impl PostgresqlImpl.
[2025-05-28T07:38:15.270+0000] {migration.py:219} INFO - Will assume transactional DDL.
[2025-05-28T07:38:15.272+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/train_models.py", line 62, in train_and_log_models
    mlflow.set_experiment("wine-quality")
  File "/home/airflow/.local/lib/python3.8/site-packages/mlflow/tracking/fluent.py", line 143, in set_experiment
    client = MlflowClient()
  File "/home/airflow/.local/lib/python3.8/site-packages/mlflow/tracking/client.py", line 134, in __init__
    self._tracking_client = TrackingServiceClient(final_tracking_uri)
  File "/home/airflow/.local/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py", line 82, in __init__
    self.store
  File "/home/airflow/.local/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/client.py", line 86, in store
    return utils._get_store(self.tracking_uri)
  File "/home/airflow/.local/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/utils.py", line 208, in _get_store
    return _tracking_store_registry.get_store(store_uri, artifact_uri)
  File "/home/airflow/.local/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/registry.py", line 42, in get_store
    return self._get_store_with_resolved_uri(resolved_store_uri, artifact_uri)
  File "/home/airflow/.local/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/registry.py", line 52, in _get_store_with_resolved_uri
    return builder(store_uri=resolved_store_uri, artifact_uri=artifact_uri)
  File "/home/airflow/.local/lib/python3.8/site-packages/mlflow/tracking/_tracking_service/utils.py", line 138, in _get_sqlalchemy_store
    return SqlAlchemyStore(store_uri, artifact_uri)
  File "/home/airflow/.local/lib/python3.8/site-packages/mlflow/store/tracking/sqlalchemy_store.py", line 180, in __init__
    mlflow.store.db.utils._verify_schema(self.engine)
  File "/home/airflow/.local/lib/python3.8/site-packages/mlflow/store/db/utils.py", line 119, in _verify_schema
    raise MlflowException(
mlflow.exceptions.MlflowException: Detected out-of-date database schema (found version 0584bdc529eb, but expected f5a4f2784254). Take a backup of your database, then run 'mlflow db upgrade <database_uri>' to migrate your database to the latest schema. NOTE: schema migration may result in database downtime - please consult your database's documentation for more detail.
[2025-05-28T07:38:15.289+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=train_ml_models, task_id=train_and_log_models, execution_date=20250528T073707, start_date=20250528T073812, end_date=20250528T073815
[2025-05-28T07:38:15.297+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 5 for task train_and_log_models (Detected out-of-date database schema (found version 0584bdc529eb, but expected f5a4f2784254). Take a backup of your database, then run 'mlflow db upgrade <database_uri>' to migrate your database to the latest schema. NOTE: schema migration may result in database downtime - please consult your database's documentation for more detail.; 3314)
[2025-05-28T07:38:15.343+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-28T07:38:15.381+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
