[2025-05-28T07:33:16.985+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_ml_models.train_and_log_models scheduled__2025-05-27T00:00:00+00:00 [queued]>
[2025-05-28T07:33:16.991+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_ml_models.train_and_log_models scheduled__2025-05-27T00:00:00+00:00 [queued]>
[2025-05-28T07:33:16.991+0000] {taskinstance.py:2193} INFO - Starting attempt 2 of 2
[2025-05-28T07:33:16.999+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): train_and_log_models> on 2025-05-27 00:00:00+00:00
[2025-05-28T07:33:17.011+0000] {standard_task_runner.py:60} INFO - Started process 2422 to run task
[2025-05-28T07:33:17.014+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'train_ml_models', 'train_and_log_models', 'scheduled__2025-05-27T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/train_models_old.py', '--cfg-path', '/tmp/tmph5sh1ekv']
[2025-05-28T07:33:17.016+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask train_and_log_models
[2025-05-28T07:33:17.059+0000] {task_command.py:423} INFO - Running <TaskInstance: train_ml_models.train_and_log_models scheduled__2025-05-27T00:00:00+00:00 [running]> on host 6bb48dadf8eb
[2025-05-28T07:33:17.122+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='train_ml_models' AIRFLOW_CTX_TASK_ID='train_and_log_models' AIRFLOW_CTX_EXECUTION_DATE='2025-05-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-27T00:00:00+00:00'
[2025-05-28T07:33:18.488+0000] {logging_mixin.py:188} INFO - üß™ –í—ã–ø–æ–ª–Ω—è–µ–º dvc pull...
[2025-05-28T07:33:18.492+0000] {logging_mixin.py:188} INFO - STDOUT: Everything is up to date.
[2025-05-28T07:33:18.494+0000] {logging_mixin.py:188} INFO - STDERR: 
[2025-05-28T07:33:19.331+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:460 ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
[2025-05-28T07:33:19.440+0000] {logging_mixin.py:188} INFO - ‚úÖ –ú–æ–¥–µ–ª—å LogisticRegression —Å–æ—Ö—Ä–∞–Ω–µ–Ω–∞ –∏ –∑–∞–ª–æ–≥–∏—Ä–æ–≤–∞–Ω–∞: /app/artifacts/LogisticRegression.pkl
[2025-05-28T07:33:19.978+0000] {logging_mixin.py:188} INFO - ‚úÖ –ú–æ–¥–µ–ª—å DecisionTree —Å–æ—Ö—Ä–∞–Ω–µ–Ω–∞ –∏ –∑–∞–ª–æ–≥–∏—Ä–æ–≤–∞–Ω–∞: /app/artifacts/DecisionTree.pkl
[2025-05-28T07:33:21.161+0000] {logging_mixin.py:188} INFO - ‚úÖ –ú–æ–¥–µ–ª—å RandomForest —Å–æ—Ö—Ä–∞–Ω–µ–Ω–∞ –∏ –∑–∞–ª–æ–≥–∏—Ä–æ–≤–∞–Ω–∞: /app/artifacts/RandomForest.pkl
[2025-05-28T07:33:21.178+0000] {python.py:202} INFO - Done. Returned value was: None
[2025-05-28T07:33:21.218+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=train_ml_models, task_id=train_and_log_models, execution_date=20250527T000000, start_date=20250528T073316, end_date=20250528T073321
[2025-05-28T07:33:21.287+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-28T07:33:21.364+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
