[2025-05-28T10:22:32.544+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: full_training_pipeline.trigger_register_best_model manual__2025-05-28T10:21:29.858363+00:00 [queued]>
[2025-05-28T10:22:32.549+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: full_training_pipeline.trigger_register_best_model manual__2025-05-28T10:21:29.858363+00:00 [queued]>
[2025-05-28T10:22:32.549+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2025-05-28T10:22:32.557+0000] {taskinstance.py:2217} INFO - Executing <Task(TriggerDagRunOperator): trigger_register_best_model> on 2025-05-28 10:21:29.858363+00:00
[2025-05-28T10:22:32.561+0000] {standard_task_runner.py:60} INFO - Started process 628 to run task
[2025-05-28T10:22:32.563+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'full_training_pipeline', 'trigger_register_best_model', 'manual__2025-05-28T10:21:29.858363+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/full_pipeline.py', '--cfg-path', '/tmp/tmpprjgx0rn']
[2025-05-28T10:22:32.569+0000] {standard_task_runner.py:88} INFO - Job 43: Subtask trigger_register_best_model
[2025-05-28T10:22:32.618+0000] {task_command.py:423} INFO - Running <TaskInstance: full_training_pipeline.trigger_register_best_model manual__2025-05-28T10:21:29.858363+00:00 [running]> on host 119f031f398a
[2025-05-28T10:22:32.676+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='full_training_pipeline' AIRFLOW_CTX_TASK_ID='trigger_register_best_model' AIRFLOW_CTX_EXECUTION_DATE='2025-05-28T10:21:29.858363+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-28T10:21:29.858363+00:00'
[2025-05-28T10:22:32.714+0000] {trigger_dagrun.py:210} INFO - Waiting for register_best_model_from_mlflow on 2025-05-28 10:22:32.676706+00:00 to become allowed state ['success'] ...
[2025-05-28T10:23:32.779+0000] {trigger_dagrun.py:210} INFO - Waiting for register_best_model_from_mlflow on 2025-05-28 10:22:32.676706+00:00 to become allowed state ['success'] ...
[2025-05-28T10:24:32.894+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/trigger_dagrun.py", line 221, in execute
    raise AirflowException(f"{self.trigger_dag_id} failed with failed states {state}")
airflow.exceptions.AirflowException: register_best_model_from_mlflow failed with failed states failed
[2025-05-28T10:24:32.902+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=full_training_pipeline, task_id=trigger_register_best_model, execution_date=20250528T102129, start_date=20250528T102232, end_date=20250528T102432
[2025-05-28T10:24:32.915+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 43 for task trigger_register_best_model (register_best_model_from_mlflow failed with failed states failed; 628)
[2025-05-28T10:24:32.970+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-28T10:24:33.000+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
